---
# Tasks to install Jenkins as a Docker container as per https://www.jenkins.io/doc/book/installing/#docker
# Also performs some pre-requiste installations of pip  and packages to allow the Ansible Docker modules to work

- name: Ensure the EPEL repo is present
  yum:
    name: epel-release
    state: present

- name: Install pip and python-devel tools (for Docker Compose)
  yum:
    name: 
      - python-pip
      - python-devel
    state: latest

- name: Update to latest version of pip
  pip:
    name: pip
    state: latest

- name: Install DockerPy module and Docker Compose
  pip:
    name: ["docker", "docker-compose"]

- name: Create temp directory for Jenkins container build
  file:
    path: ~/jenkins-pro
    state: directory
    mode: '0755'

- name: Copy the custom Dockerfile for Jenkins
  copy:
    src: files/jenkins-pro
    dest: ~/jenkins-pro
    mode: '0755'

- name: Start services using Docker Compose
  docker_compose:
    project_name: devops-playground
    definition:
      version: '2.4'
      services:
        artifactory:
          container_name: artifactory
          image: docker.bintray.io/jfrog/artifactory-oss:latest
          networks:
            - jenkins
          ports:
            - "8081:8081"
            - "8082:8082"
          volumes:
            - artifactory-data:/var/opt/jfrog/artifactory
        docker:
          container_name: jenkins-docker
          environment:
            DOCKER_TLS_CERTDIR: "/certs"
          image: docker
          networks:
            jenkins:
              aliases:
                - docker
          volumes:
            - jenkins-docker-certs:/certs/client
            - jenkins-data:/var/jenkins/home
        jenkins:
          build:
            context: ~/jenkins-pro
          container_name: jenkins
          networks:
            - jenkins
          ports:
            - "8080:8080"
            - "50000:50000"
          volumes:
            - jenkins-docker-certs:/certs/client:ro
            - jenkins-data:/var/jenkins/home
      networks:
        jenkins:
      volumes:
        jenkins-docker-certs:
        jenkins-data:
        artifactory-data:

- name: Cleanup build directory for custom container
  file:
    path: ~/jenkins-pro
    state: absent